export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_QUESTIONS_REQUEST = 'USER_QUESTIONS_REQUEST'
export const USER_QUESTIONS_SUCCESS = 'USER_QUESTIONS_SUCCESS'
export const USER_QUESTIONS_FAIL = 'USER_QUESTIONS_FAIL'

export const USER_COMMENTS_REQUEST = 'USER_COMMENTS_REQUEST'
export const USER_COMMENTS_SUCCESS = 'USER_COMMENTS_SUCCESS'
export const USER_COMMENTS_FAIL = 'USER_COMMENTS_FAIL'

export const USER_UPDATE_ACCOUNT_REQUEST = 'USER_UPDATE_ACCOUNT_REQUEST'
export const USER_UPDATE_ACCOUNT_SUCCESS = 'USER_UPDATE_ACCOUNT_SUCCESS'
export const USER_UPDATE_ACCOUNT_FAIL = 'USER_UPDATE_ACCOUNT_FAIL'
